"""Substantive resume recommendations grounded in docs/resume_principles.md.

This replaces the single-word `get_targeted_replacements` path for the public
resume-review tool. Returns full bullet rewrites, missing-skill flags, summary
rewrites, etc. - not one-word verb swaps.
"""
from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any, Dict, List

logger = logging.getLogger(__name__)

# docs/resume_principles.md is generated by backend/scripts/build_resume_principles.py
_PRINCIPLES_PATH = (
    Path(__file__).resolve().parents[3] / "docs" / "resume_principles.md"
)

_FALLBACK_PRINCIPLES = """\
# Resume principles (fallback)

When critiquing early-career resumes for consulting / IB / tech:

- Lead bullets with strong action verbs (Led, Built, Engineered, Architected, Analyzed).
- Every bullet should answer: what you did + how + measurable impact.
- Quantify. Dollar amounts, percentages, user counts, time saved, throughput.
- Mirror the JD's keywords where truthful. Don't fabricate.
- Drop fluff: "team player", "passionate", "hard-working".
- One page for 0-2 years of experience.
- Education first if currently in school; Experience first after graduation.
- Skills section: relevance order, not alphabetical. Skip Microsoft Word.
- For consulting: leadership, structured thinking, quant rigor.
- For IB: modeling exposure, deal context, Excel/PowerPoint, accuracy.
- For tech: shipped projects with measurable usage, language/framework specificity.
"""


def _load_principles() -> str:
    try:
        return _PRINCIPLES_PATH.read_text(encoding="utf-8")
    except FileNotFoundError:
        logger.warning("resume_principles.md not found at %s, using fallback", _PRINCIPLES_PATH)
        return _FALLBACK_PRINCIPLES
    except Exception as exc:
        logger.warning("Could not load resume_principles.md: %s", exc)
        return _FALLBACK_PRINCIPLES


VALID_CATEGORIES = {
    "bullet_rewrite",
    "missing_skill",
    "weak_summary",
    "missing_metric",
    "skill_alignment",
    "structure",
    "verb_strength",
}
VALID_SEVERITIES = {"high", "medium", "low"}


def generate_substantive_recommendations(
    resume_text: str,
    job_description: str,
    openai_client,
    job_title: str = "",
    company: str = "",
) -> List[Dict[str, Any]]:
    """Return 6-12 substantive recommendations grounded in resume principles.

    Each recommendation:
        {
          "id": int,
          "category": one of VALID_CATEGORIES,
          "severity": "high" | "medium" | "low",
          "section": "Experience" | "Summary" | "Skills" | ...,
          "original_text": exact substring of resume_text (or "" for additions),
          "suggested_text": full replacement / new line,
          "rationale": one sentence tying it to the specific JD,
          "principle": short label for the rule being applied,
        }
    """
    principles = _load_principles()

    prompt = f"""You are an elite resume coach for early-career consulting / investment banking /
tech recruiting. You will analyze a candidate's resume against a specific job
description and produce SUBSTANTIVE recommendations. Not single-word verb swaps.
Real bullet rewrites, missing-skill flags, summary rewrites, metric additions.

Use the principles below to ground your reasoning.

## RESUME PRINCIPLES (reference)
{principles[:8000]}

## CANDIDATE RESUME
{resume_text[:6000]}

## TARGET JOB
Title: {job_title or 'Not specified'}
Company: {company or 'Not specified'}

Job description:
{job_description[:4000]}

## OUTPUT FORMAT
Return strict JSON: {{ "recommendations": [<rec>, ...] }} with 6-12 recommendations.

Each rec has these fields:
- "category": one of "bullet_rewrite", "missing_skill", "weak_summary",
  "missing_metric", "skill_alignment", "structure", "verb_strength"
- "severity": "high" (costs interviews), "medium" (notable gap), "low" (polish)
- "section": which resume section ("Experience", "Summary", "Skills", "Education",
  "Projects", "Leadership")
- "original_text": the EXACT text from the resume to replace, character-for-character.
  May be a full bullet, a summary sentence, a skill line. For an addition (new bullet
  or new line), use "" and the recommendation will be displayed as "Add: <suggested_text>".
- "suggested_text": the full replacement text. Concrete, tailored to the JD.
- "rationale": ONE sentence on why this matters for THIS job, mentioning something
  specific from the JD (a skill they asked for, a responsibility, the company).
- "principle": short reference to the principle being applied (e.g., "Quantify impact",
  "Mirror JD keywords", "Lead with strong action verb", "Drop generic filler")

## HARD RULES
1. "original_text" must be a verbatim substring of the resume. Copy it character-for-character.
   If your suggested_text replaces text, that text must exist in the resume.
2. NEVER fabricate facts, metrics, companies, dates, or technologies the candidate doesn't
   have. If you want them to add a number they don't have, phrase the suggested_text as a
   placeholder, e.g. "Engineered a Python pipeline that processed [X GB/day] across [N users],
   reducing latency by [Y%]." Use square brackets for placeholders the candidate must fill in.
3. NEVER change company names, school names, degree names, dates, or job titles.
4. Suggested rewrites should sound like the candidate, at the candidate's seniority level.
   Don't make a junior sound like a VP.
5. Prioritize changes that map directly to the JD's stated requirements / responsibilities.
6. Every recommendation must be at least 10x more valuable than a single-word swap.
   If you only have single-word swaps to make, write fewer recommendations.
7. Order recommendations by severity (high first), then by section.

Return ONLY the JSON object, no preamble."""

    try:
        response = openai_client.chat.completions.create(
            model="gpt-4o",
            messages=[
                {
                    "role": "system",
                    "content": "You are a senior resume coach. You always return valid JSON only.",
                },
                {"role": "user", "content": prompt},
            ],
            response_format={"type": "json_object"},
            temperature=0.3,
            max_tokens=4000,
        )
        raw_json = response.choices[0].message.content or "{}"
        parsed = json.loads(raw_json)
    except Exception as exc:
        logger.error("Resume recommender failed: %s", exc)
        return []

    raw_recs = parsed.get("recommendations") or []
    valid: List[Dict[str, Any]] = []
    next_id = 0
    for r in raw_recs:
        if not isinstance(r, dict):
            continue
        original = (r.get("original_text") or "").strip()
        suggested = (r.get("suggested_text") or "").strip()
        if not suggested:
            continue
        # If original is non-empty, it MUST exist verbatim in the resume so the patcher can find it.
        if original and original not in resume_text:
            logger.warning("Recommender returned original_text not in resume; skipping. text=%r", original[:80])
            continue

        category = r.get("category") or "bullet_rewrite"
        if category not in VALID_CATEGORIES:
            category = "bullet_rewrite"
        severity = r.get("severity") or "medium"
        if severity not in VALID_SEVERITIES:
            severity = "medium"

        valid.append({
            "id": next_id,
            "category": category,
            "severity": severity,
            "section": r.get("section") or "",
            "original_text": original,
            "suggested_text": suggested,
            "rationale": (r.get("rationale") or "").strip(),
            "principle": (r.get("principle") or "").strip(),
        })
        next_id += 1

    # Sort: high severity first, then medium, then low.
    sev_order = {"high": 0, "medium": 1, "low": 2}
    valid.sort(key=lambda x: (sev_order.get(x["severity"], 3), x.get("section", "")))
    return valid
