/*
 * SEO PREVIEW: cold email (REACH). Route: /seo-preview/cold-email-goldman
 * Showcase mirrors the email-gen output (reply_generation.py): subject, body,
 * personalization label + lead hook, warmth tier. House style: no em dashes.
 */
import { Helmet } from 'react-helmet-async';
import { Mail, UserSearch, PenLine, Send, BadgeCheck, CornerDownRight } from 'lucide-react';
import {
  BRAND, BRAND_DARK, INK, kicker, PreviewNav, PreviewFooter, PreviewHero,
  ProblemSection, StatStrip, ShowcaseSection, HowItWorks, FAQ, PreviewCTA, InlineEmailCapture, ExitIntentCapture,
} from './_shared';

const emailCapture = {
  eyebrow: 'NOT RECRUITING YET?',
  heading: 'Get the weekly banking recruiting digest',
  subtext: 'New cold email angles, interview question drops, and deadline changes, every week. Built for students breaking into investment banking.',
  buttonText: 'Send me the digest',
  cluster: 'banking',
};

const ColdEmailPreview = () => {
  return (
    <div className="min-h-screen w-full" style={{ fontFamily: "'DM Sans', system-ui, sans-serif", background: '#FFFFFF' }}>
      <Helmet>
        <title>Cold Email Goldman Sachs Analysts: Template + Generator</title>
        <meta name="robots" content="noindex" />
      </Helmet>

      <PreviewNav />

      <PreviewHero
        EyebrowIcon={Mail}
        eyebrow="COLD EMAIL · GOLDMAN SACHS"
        line1={<>Cold email a <span style={{ color: BRAND }}>Goldman Sachs</span> analyst</>}
        line2="and actually get a reply"
        lead="Offerloop finds the analyst, writes a personalized cold email built on what you have in common, and shows you why every line works. Paste a name, get a reply-worthy draft in ten seconds."
        chips={['Verified analyst emails', 'Personalized, not templated', 'Draft in 10 seconds']}
      />

      <ProblemSection heading="The template is everywhere. The reply isn't.">
        Every guide hands you the same four-sentence cold email. What actually takes hours is the real
        work: figuring out which Goldman analyst to email, finding a verified address, and personalizing
        twenty emails so none of them read like a mail merge. Most students send five generic emails,
        get silence, and stop.
      </ProblemSection>

      <StatStrip
        heading="COLD-EMAILING GOLDMAN, BY THE NUMBERS"
        stats={[
          { value: 'first.last@gs.com', label: "Goldman Sachs's verified work email format" },
          { value: '2,400+', label: 'Goldman analysts and associates reachable through Offerloop' },
          { value: 'Tue-Thu, 9-11am', label: 'when banking cold emails are most likely to be opened' },
        ]}
      />

      <ShowcaseSection
        heading="The cold email Offerloop writes you"
        intro="A real example: a warm email to a Goldman Sachs TMT analyst, with every personalized line traced back to where it came from."
        caption="Sample output. Your real draft is generated from the analyst's profile and your resume, and you edit it before sending."
      >
        <div className="rounded-[6px]" style={{ border: '1px solid #E2E8F0', overflow: 'hidden', boxShadow: '0 30px 70px -28px rgba(15,23,42,0.32)', background: '#fff' }}>
          <div style={{ height: '4px', background: `linear-gradient(90deg, ${BRAND}, #60A5FA)` }} />

          {/* draft header */}
          <div className="flex items-center gap-2.5 px-6 py-3.5" style={{ background: '#F8FAFC', borderBottom: '1px solid #E2E8F0' }}>
            <Mail className="w-4 h-4" style={{ color: BRAND }} />
            <span style={{ fontSize: '13px', fontWeight: 700, color: INK }}>Draft generated by Offerloop</span>
            <span style={{ marginLeft: 'auto', fontSize: '11px', fontWeight: 700, color: '#15803D', background: '#DCFCE7', borderRadius: '999px', padding: '3px 10px' }}>WARM · USC ALUMNI</span>
          </div>

          {/* to + subject */}
          <div className="px-6 py-3" style={{ borderBottom: '1px solid #F1F5F9' }}>
            <div className="flex items-center gap-2" style={{ fontSize: '13px', color: '#475569', marginBottom: '6px' }}>
              <span style={{ color: '#94A3B8', width: '52px' }}>To</span>
              <span style={{ fontWeight: 600, color: INK }}>Priya Shah</span>
              <span style={{ color: '#64748B' }}>priya.shah@gs.com</span>
              <span className="inline-flex items-center gap-1" style={{ fontSize: '11px', fontWeight: 700, color: BRAND_DARK }}>
                <BadgeCheck className="w-3.5 h-3.5" /> verified
              </span>
            </div>
            <div className="flex items-center gap-2" style={{ fontSize: '13px' }}>
              <span style={{ color: '#94A3B8', width: '52px' }}>Subject</span>
              <span style={{ fontWeight: 600, color: INK }}>USC Marshall sophomore, chasing your corner of TMT</span>
            </div>
          </div>

          {/* body */}
          <div className="px-6 py-5" style={{ fontSize: '14px', lineHeight: 1.75, color: '#334155' }}>
            <p style={{ marginBottom: '12px' }}>Hi Priya,</p>
            <p style={{ marginBottom: '12px' }}>
              Fellow Trojan here. <mark style={{ background: '#EFF5FF', color: '#1E3A5F', padding: '1px 3px', borderRadius: '2px' }}>Your Marshall honors thesis on vertical SaaS valuation</mark> is almost exactly the lane I'm chasing, and I noticed you've <mark style={{ background: '#EFF5FF', color: '#1E3A5F', padding: '1px 3px', borderRadius: '2px' }}>stayed on enterprise-software deals since converting from your TMT summer</mark>.
            </p>
            <p style={{ marginBottom: '12px' }}>
              One question I'd love 15 minutes on: when you recruited, how did you signal interest in software M&amp;A specifically, not TMT broadly?
            </p>
            <p style={{ marginBottom: '12px' }}>Happy to work around your calendar.</p>
            <p style={{ marginBottom: '12px' }}>Go Trojans,</p>
            <p>Daniel Park<br /><span style={{ color: '#94A3B8' }}>USC Marshall '28</span></p>
          </div>

          {/* personalization X-ray */}
          <div className="px-6 py-4" style={{ background: '#FAFBFF', borderTop: '1px solid #F1F5F9' }}>
            <p style={{ ...kicker, marginBottom: '8px' }}>WHY THIS EMAIL WORKS</p>
            {[
              ['"your Marshall honors thesis on vertical SaaS valuation"', "Priya's USC record: her honors thesis topic, a detail almost no one would surface by hand"],
              ['"stayed on enterprise-software deals since converting from your TMT summer"', 'the deal pattern across her Goldman experience, summer and full-time'],
              ['"software M&A specifically, not TMT broadly"', 'the question Offerloop built by matching her sub-focus to your stated interest in vertical software'],
            ].map(([phrase, src], i) => (
              <p key={i} className="flex items-start gap-1.5" style={{ fontSize: '12px', color: '#64748B', marginBottom: i < 2 ? '5px' : 0 }}>
                <CornerDownRight className="w-3 h-3 flex-shrink-0" style={{ marginTop: '3px', color: '#94A3B8' }} />
                <span><span style={{ color: '#334155', fontWeight: 600 }}>{phrase}</span> <span style={{ fontStyle: 'italic' }}>generated from {src}</span></span>
              </p>
            ))}
          </div>
        </div>
      </ShowcaseSection>

      <HowItWorks
        heading="How it works"
        steps={[
          { Icon: UserSearch, t: 'Pick the analyst', d: 'Search Goldman Sachs in Offerloop and pick an analyst, or paste a LinkedIn URL. You get a verified email address back.' },
          { Icon: PenLine, t: 'Offerloop drafts the email', d: 'It reads their background and yours, finds the strongest real connection, and writes a personalized draft in your voice.' },
          { Icon: Send, t: 'Edit one line and send', d: 'Tweak the personalization line so it sounds like you, then send or push the whole batch to Gmail drafts.' },
        ]}
      />

      <FAQ items={[
        { q: 'What should the subject line be for a cold email to a Goldman analyst?', a: "Lead with your school and the firm: \"USC Marshall '28 + a question about Goldman TMT.\" A shared-school subject line gets opened far more than a generic \"Networking request.\" Offerloop writes the subject line for you." },
        { q: 'How long should an investment banking cold email be?', a: 'Four to five sentences, under 120 words. An analyst reads it on their phone between tasks. Anything longer gets archived unread.' },
        { q: 'What is the Goldman Sachs email format?', a: 'Goldman work emails are first.last@gs.com. Offerloop returns the verified address directly, so you never have to guess the format or risk a bounce.' },
        { q: 'When is the best time to send a cold email to a banker?', a: 'Tuesday through Thursday, 9 to 11am their time. Analysts clear their inbox before the day\'s deal work buries it. Friday and Sunday-night emails get lost.' },
        { q: "Should I follow up if an analyst doesn't reply?", a: 'Once, after five to seven business days, two lines on the same thread. After that, move on. A third email lowers your odds with everyone in their network.' },
      ]} />

      <InlineEmailCapture {...emailCapture} />

      <PreviewCTA
        eyebrow="STOP STARING AT A BLANK EMAIL"
        headline="Draft a cold email to a Goldman analyst right now"
        subhead="Find the analyst, get a verified email, and generate a personalized draft. Free."
        buttonText="Reach out to your first Goldman analyst"
        to="/find?company=Goldman%20Sachs"
        footnote="One click opens Offerloop with Goldman Sachs already loaded. No credit card."
      />

      <PreviewFooter />
      <ExitIntentCapture {...emailCapture} />
    </div>
  );
};

export default ColdEmailPreview;
