/**
 * QueuePanel — the "Suggested For You" tab inside NetworkTracker.
 *
 * Phase 1 behavior:
 *  - Auto-generates on first visit if the user has no active queue and the
 *    tier is Pro/Elite.
 *  - Free tier sees a static teaser (queueTeaserFixture) with a Pro CTA —
 *    the Refine / Approve / Dismiss actions are all disabled so we never
 *    hit the backend from Free.
 *  - Pro/Elite can click "Refine" to open the 3-field sheet and manually
 *    re-generate.
 *  - Polls /api/queue/status/{id} every 3s while status === "processing".
 *
 * States rendered:
 *  - loading        (skeleton while initial getCurrent call runs)
 *  - empty          (no queue yet — prompt to generate)
 *  - in_progress    (backend is building the queue — shimmer + progress text)
 *  - pending_review (cards rendered, approve/dismiss enabled)
 *  - all_reviewed   (every contact reviewed — prompt to generate the next)
 *  - error          (PDL / email / write failure — offer retry)
 */
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { Lock, Sparkles, RefreshCw, Loader2, Info, Check } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import { useSubscription } from "@/hooks/useSubscription";
import {
  apiService,
  type QueueContact,
  type QueueDismissReason,
  type QueueDoc,
  type QueueFilters,
} from "@/services/api";
import { QUEUE_TEASER_CONTACTS } from "@/data/queueTeaserFixture";
import { QueueContactCard } from "./QueueContactCard";
import { DismissModal } from "./DismissModal";
import { RefineSheet } from "./RefineSheet";

// ---------- small helpers ----------

function isTerminalStatus(status: string | undefined): boolean {
  return (
    status === "pending_review" ||
    status === "completed_partial" ||
    status === "failed" ||
    status === "failed_pdl" ||
    status === "failed_emails" ||
    status === "failed_write" ||
    status === "archived" ||
    status === "expired"
  );
}

function isFailureStatus(status: string | undefined): boolean {
  return (
    status === "failed" ||
    status === "failed_pdl" ||
    status === "failed_emails" ||
    status === "failed_write"
  );
}

function pendingContacts(queue: QueueDoc | null | undefined): QueueContact[] {
  if (!queue) return [];
  // Backend writes contact-level status as "pending" (queue-level status
  // "pending_review" is a separate concept — see queue_service.py module doc).
  return (queue.contacts || []).filter((c) => c.status === "pending");
}

// ---------- component ----------

interface QueuePanelProps {
  /** Whether this tab is currently visible — used to trigger auto-generate. */
  isActive: boolean;
}

export function QueuePanel({ isActive }: QueuePanelProps) {
  const { toast } = useToast();
  const queryClient = useQueryClient();
  const { subscription, loading: subLoading } = useSubscription();

  const tier = subscription?.tier || "free";
  const isFree = tier === "free";
  const hasProAccess = tier === "pro" || tier === "elite";

  const [pollingQueueId, setPollingQueueId] = useState<string | null>(null);
  const [refineOpen, setRefineOpen] = useState(false);
  const [dismissTarget, setDismissTarget] = useState<QueueContact | null>(null);
  const [localApproved, setLocalApproved] = useState<Set<string>>(new Set());
  const [localDismissed, setLocalDismissed] = useState<Set<string>>(new Set());
  const autoGeneratedRef = useRef(false);

  // --- queries ---

  const currentQueueQuery = useQuery({
    queryKey: ["queue", "current"],
    queryFn: async () => {
      const res = await apiService.getCurrentQueue();
      if ("error" in res) throw new Error(res.error);
      return res.queue;
    },
    enabled: hasProAccess,
  });

  const currentQueue = currentQueueQuery.data ?? null;
  const currentStatus = currentQueue?.status;

  // Poll while the queue is still generating.
  useEffect(() => {
    if (!pollingQueueId) return;
    let cancelled = false;

    const tick = async () => {
      try {
        const res = await apiService.getQueueStatus(pollingQueueId);
        if (cancelled) return;
        if ("error" in res) {
          toast({ title: "Failed to poll queue status", variant: "destructive" });
          setPollingQueueId(null);
          return;
        }
        if (isTerminalStatus(res.status)) {
          setPollingQueueId(null);
          // Reset the optimistic review state — we're replacing the queue.
          setLocalApproved(new Set());
          setLocalDismissed(new Set());
          queryClient.invalidateQueries({ queryKey: ["queue", "current"] });
          if (isFailureStatus(res.status)) {
            toast({
              title: "Queue generation failed",
              description: res.error || "Please try again or refine your filters.",
              variant: "destructive",
            });
          }
        }
      } catch (_err) {
        if (cancelled) return;
        setPollingQueueId(null);
      }
    };

    const interval = setInterval(tick, 3000);
    // Fire once immediately too.
    tick();
    return () => {
      cancelled = true;
      clearInterval(interval);
    };
  }, [pollingQueueId, queryClient, toast]);

  // --- generate mutation ---

  const generateMutation = useMutation({
    mutationFn: async (filters?: QueueFilters) => {
      const res = await apiService.generateQueue({ filters });
      return res;
    },
    onSuccess: (data, filters) => {
      // The response is a union: success has `ok: true`, failure has `error`.
      if ("error" in data) {
        if (data.needsRefine) {
          // Silent on auto-generate; the sheet is the call to action.
          setRefineOpen(true);
          if (filters) {
            // User already filled the sheet — tell them why we bounced.
            toast({
              title: "We need a bit more info",
              description: data.error || "Tell us a company or title to search.",
            });
          }
          return;
        }
        if (data.upgradeRequired) {
          toast({
            title: "Upgrade required",
            description: data.error || "Upgrade to Pro to generate queues.",
            variant: "destructive",
          });
          return;
        }
        toast({
          title: "Could not generate queue",
          description: data.error || "Please try again.",
          variant: "destructive",
        });
        return;
      }
      // ok === true path
      setPollingQueueId(data.queueId);
      setRefineOpen(false);
      setLocalApproved(new Set());
      setLocalDismissed(new Set());
      toast({
        title: "Building your queue…",
        description: data.isFreeWeekly
          ? "Complimentary — no credits charged for your weekly queue."
          : `Charged ${data.creditsCharged} credits.`,
      });
    },
    onError: () => {
      toast({
        title: "Could not generate queue",
        description: "Please try again.",
        variant: "destructive",
      });
    },
  });

  // Auto-generate on first visit for Pro/Elite when there's nothing to show.
  useEffect(() => {
    if (!isActive) return;
    if (autoGeneratedRef.current) return;
    if (!hasProAccess) return;
    if (subLoading) return;
    if (currentQueueQuery.isLoading) return;
    if (pollingQueueId) return;
    if (currentQueue && (currentQueue.contacts || []).length > 0) return;
    if (currentStatus === "processing") {
      // Backend already has a job running — resume polling.
      if (currentQueue?.id) setPollingQueueId(currentQueue.id);
      autoGeneratedRef.current = true;
      return;
    }
    autoGeneratedRef.current = true;
    generateMutation.mutate(undefined);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [isActive, hasProAccess, subLoading, currentQueueQuery.isLoading, currentQueue, currentStatus, pollingQueueId]);

  // --- approve / dismiss mutations ---

  const approveMutation = useMutation({
    mutationFn: async (contact: QueueContact) => {
      if (!currentQueue) throw new Error("No active queue");
      const res = await apiService.approveQueueContact(currentQueue.id, contact.id);
      if ("error" in res) throw new Error(res.error);
      return { res, contact };
    },
    onMutate: ({ id }: QueueContact) => {
      setLocalApproved((prev) => new Set(prev).add(id));
    },
    onSuccess: ({ res, contact }) => {
      const composeUrl = res.composeUrl;
      toast({
        title: `Added ${contact.name || "contact"} to your pipeline`,
        description: composeUrl
          ? "Gmail isn't connected — we opened a compose window instead."
          : "We drafted an email for you.",
      });
      if (composeUrl) window.open(composeUrl, "_blank");
      queryClient.invalidateQueries({ queryKey: ["trackerContacts"] });
    },
    onError: (_err, contact) => {
      setLocalApproved((prev) => {
        const next = new Set(prev);
        next.delete(contact.id);
        return next;
      });
      toast({ title: "Failed to approve", variant: "destructive" });
    },
  });

  const dismissMutation = useMutation({
    mutationFn: async ({
      contact,
      reason,
    }: {
      contact: QueueContact;
      reason: QueueDismissReason;
    }) => {
      if (!currentQueue) throw new Error("No active queue");
      const res = await apiService.dismissQueueContact(currentQueue.id, contact.id, reason);
      if ("error" in res) throw new Error(res.error);
      return { res, contact, reason };
    },
    onMutate: ({ contact }) => {
      setLocalDismissed((prev) => new Set(prev).add(contact.id));
    },
    onSuccess: ({ contact }) => {
      toast({ title: `Dismissed ${contact.name || "contact"}` });
      setDismissTarget(null);
    },
    onError: (_err, { contact }) => {
      setLocalDismissed((prev) => {
        const next = new Set(prev);
        next.delete(contact.id);
        return next;
      });
      toast({ title: "Failed to dismiss", variant: "destructive" });
    },
  });

  // --- derived state ---

  const visibleContacts = useMemo(() => {
    const pending = pendingContacts(currentQueue);
    return pending.filter((c) => !localDismissed.has(c.id) && !localApproved.has(c.id));
  }, [currentQueue, localApproved, localDismissed]);

  const isGenerating =
    generateMutation.isPending ||
    currentStatus === "processing" ||
    Boolean(pollingQueueId);

  const totalReviewed = useMemo(() => {
    if (!currentQueue) return 0;
    return localApproved.size + localDismissed.size;
  }, [currentQueue, localApproved, localDismissed]);

  const totalPending = pendingContacts(currentQueue).length;
  const allReviewed = currentQueue && totalPending > 0 && visibleContacts.length === 0;

  // --- handlers ---

  const handleGenerateClick = useCallback(() => {
    if (isFree) {
      toast({
        title: "Upgrade to Pro",
        description: "Agentic queue is a Pro/Elite feature.",
      });
      return;
    }
    generateMutation.mutate(undefined);
  }, [isFree, generateMutation, toast]);

  const handleRefineSubmit = useCallback(
    (filters: QueueFilters) => {
      generateMutation.mutate(filters);
    },
    [generateMutation]
  );

  // --- free tier teaser ---

  if (isFree) {
    return (
      <div className="p-3 space-y-3">
        <div className="rounded-[6px] bg-gradient-to-br from-[#EFF6FF] to-white border border-[#3B82F6]/20 px-4 py-4 flex items-start gap-3">
          <div className="flex-1 min-w-0">
            <p className="text-sm font-semibold text-gray-900">
              Your personal networking coach — on Pro.
            </p>
            <p className="text-xs text-gray-600 mt-1 leading-relaxed">
              Every Monday we surface 5 pre-vetted contacts who match your target companies and
              roles, with drafted emails ready to send. Approve with one click.
            </p>
            <a
              href="/pricing"
              className="mt-2 inline-flex items-center gap-1.5 text-xs font-semibold text-[#3B82F6] hover:underline"
            >
              <Lock className="w-3 h-3" />
              Upgrade to Pro
            </a>
          </div>
        </div>
        <p className="text-[11px] font-medium uppercase tracking-wide text-gray-400 px-1">
          Preview
        </p>
        <div className="space-y-2 opacity-75 pointer-events-none">
          {QUEUE_TEASER_CONTACTS.map((c) => (
            <QueueContactCard
              key={c.id}
              contact={c}
              onApprove={() => {}}
              onDismiss={() => {}}
              readOnly
            />
          ))}
        </div>
      </div>
    );
  }

  // --- pro/elite states ---

  // Loading (initial fetch of current queue)
  if (currentQueueQuery.isLoading && !currentQueue) {
    return (
      <div className="p-3 space-y-2">
        {[0, 1, 2].map((i) => (
          <div key={i} className="h-28 rounded-[6px] bg-gray-50 border border-gray-100 animate-pulse" />
        ))}
      </div>
    );
  }

  // Generation in progress
  if (isGenerating && visibleContacts.length === 0) {
    return (
      <div className="p-3 space-y-3">
        <div className="rounded-[6px] bg-[#FAFBFF] border border-[#3B82F6]/20 px-4 py-4 flex items-center gap-3">
          <Loader2 className="w-4 h-4 text-[#3B82F6] animate-spin flex-shrink-0" />
          <div className="flex-1 min-w-0">
            <p className="text-sm font-semibold text-gray-900">Building your queue…</p>
            <p className="text-xs text-gray-500 mt-0.5">
              Searching PDL, scoring warmth, and drafting emails. Takes about 30 seconds.
            </p>
          </div>
        </div>
        <div className="space-y-2">
          {[0, 1, 2].map((i) => (
            <div
              key={i}
              className="h-28 rounded-[6px] bg-gray-50 border border-gray-100 animate-pulse"
            />
          ))}
        </div>
      </div>
    );
  }

  // Generation failure
  if (currentQueue && isFailureStatus(currentStatus)) {
    return (
      <div className="p-3">
        <div className="rounded-[6px] bg-red-50 border border-red-100 px-4 py-4">
          <p className="text-sm font-semibold text-red-700">Queue generation failed</p>
          <p className="text-xs text-red-600 mt-1">
            {currentQueue.error || "Something went wrong. Your credits were refunded."}
          </p>
          <div className="mt-3 flex items-center gap-2">
            <button
              type="button"
              onClick={handleGenerateClick}
              disabled={generateMutation.isPending}
              className="inline-flex items-center gap-1.5 text-xs font-semibold px-3 py-1.5 rounded-[3px] bg-[#3B82F6] text-white hover:bg-[#2563EB] disabled:opacity-40"
            >
              <RefreshCw className="w-3.5 h-3.5" />
              Try again
            </button>
            <button
              type="button"
              onClick={() => setRefineOpen(true)}
              className="text-xs font-medium text-gray-600 hover:text-gray-900"
            >
              Refine filters
            </button>
          </div>
        </div>
      </div>
    );
  }

  // All reviewed
  if (allReviewed) {
    return (
      <div className="p-3 space-y-3">
        <div className="rounded-[6px] bg-[#F0FDF4] border border-green-100 px-4 py-5 text-center">
          <div className="w-10 h-10 rounded-full bg-green-100 flex items-center justify-center mx-auto mb-2">
            <Check className="w-5 h-5 text-green-600" />
          </div>
          <p className="text-sm font-semibold text-gray-900">You're all caught up!</p>
          <p className="text-xs text-gray-500 mt-1">
            Reviewed {totalReviewed} contact{totalReviewed === 1 ? "" : "s"} from this queue.
          </p>
          <div className="mt-3 flex items-center justify-center gap-2">
            <button
              type="button"
              onClick={handleGenerateClick}
              className="inline-flex items-center gap-1.5 text-xs font-semibold px-3 py-1.5 rounded-[3px] bg-[#3B82F6] text-white hover:bg-[#2563EB]"
            >
              <Sparkles className="w-3.5 h-3.5" />
              Generate another
            </button>
            <button
              type="button"
              onClick={() => setRefineOpen(true)}
              className="text-xs font-medium text-gray-600 hover:text-gray-900"
            >
              Refine
            </button>
          </div>
        </div>
        <RefineSheet
          open={refineOpen}
          onOpenChange={setRefineOpen}
          initialFilters={currentQueue?.filters}
          isSubmitting={generateMutation.isPending}
          onSubmit={handleRefineSubmit}
        />
      </div>
    );
  }

  // Empty (no queue yet)
  if (!currentQueue || visibleContacts.length === 0) {
    return (
      <div className="p-3">
        <div className="rounded-[6px] border border-gray-100 bg-white px-4 py-5 text-center">
          <p className="text-sm font-semibold text-gray-900">No suggestions yet</p>
          <p className="text-xs text-gray-500 mt-1">
            Generate your first queue of 5 pre-vetted contacts.
          </p>
          <div className="mt-3 flex items-center justify-center gap-2">
            <button
              type="button"
              onClick={handleGenerateClick}
              disabled={generateMutation.isPending}
              className="inline-flex items-center gap-1.5 text-xs font-semibold px-3 py-1.5 rounded-[3px] bg-[#3B82F6] text-white hover:bg-[#2563EB] disabled:opacity-40"
            >
              <Sparkles className="w-3.5 h-3.5" />
              Generate queue
            </button>
            <button
              type="button"
              onClick={() => setRefineOpen(true)}
              className="text-xs font-medium text-gray-600 hover:text-gray-900"
            >
              Refine
            </button>
          </div>
        </div>
        <RefineSheet
          open={refineOpen}
          onOpenChange={setRefineOpen}
          initialFilters={currentQueue?.filters}
          isSubmitting={generateMutation.isPending}
          onSubmit={handleRefineSubmit}
        />
      </div>
    );
  }

  // Pending review — render cards
  return (
    <div className="p-3 space-y-3">
      <div className="flex items-center justify-between px-1">
        <div className="flex items-center gap-1.5 text-[11px] text-gray-500">
          <Info className="w-3 h-3" />
          <span>
            {visibleContacts.length} of {totalPending} to review
          </span>
        </div>
        <button
          type="button"
          onClick={() => setRefineOpen(true)}
          className="text-[11px] font-medium text-gray-500 hover:text-[#3B82F6]"
        >
          Refine
        </button>
      </div>

      <div className="space-y-2">
        {visibleContacts.map((contact) => (
          <QueueContactCard
            key={contact.id}
            contact={contact}
            onApprove={() => approveMutation.mutate(contact)}
            onDismiss={() => setDismissTarget(contact)}
            isApproving={approveMutation.isPending && approveMutation.variables?.id === contact.id}
            isDismissing={
              dismissMutation.isPending && dismissMutation.variables?.contact.id === contact.id
            }
          />
        ))}
      </div>

      <DismissModal
        open={dismissTarget !== null}
        contactName={dismissTarget?.name || dismissTarget?.firstName || "this contact"}
        isSubmitting={dismissMutation.isPending}
        onCancel={() => setDismissTarget(null)}
        onConfirm={(reason) => {
          if (dismissTarget) {
            dismissMutation.mutate({ contact: dismissTarget, reason });
          }
        }}
      />

      <RefineSheet
        open={refineOpen}
        onOpenChange={setRefineOpen}
        initialFilters={currentQueue?.filters}
        isSubmitting={generateMutation.isPending}
        onSubmit={handleRefineSubmit}
      />
    </div>
  );
}
